### ISSUE TITLE
Changelog seems out of date

### ISSUE THREAD

**Issue by jayqui-omada** [capistrano/bundler#119]
Hi there, I'm wondering what breaking changes there might be in versions >=2?

**Comment by mattbrictson** [comment]
There is no `capistrano-bundler` version >= 2. We're at 1.6.0. 🙂 

Maybe you are referring to the bundler project? The bundler release notes are kept here: https://bundler.io/v2.0/whats_new.html

**Comment by jayqui-omada** [comment]
Aha, this was the wrong repo! I meant to be looking at https://github.com/rubygems/bundler/blob/master/CHANGELOG.md!

![image](https://media.giphy.com/media/AjYsTtVxEEBPO/giphy.gif)
