### ISSUE TITLE
Bundler emits warning about "replacing the local value of without"

### ISSUE THREAD

**Issue by Fjan** [capistrano/bundler#125]
*To reproduce:*
Do a deploy with capistrano-bundler version 2.0.0 with default options
It will cause bundler to emit a warning: 
`You are replacing the current local value of without, which is currently "development:test"`
This warning is harmless, the deploy works normally.

*Analysis*
With https://github.com/capistrano/bundler/pull/122 Capistrano-bundler started using `bundler config` instead of `bundler install`. It turns out `bundler install` wants a space separated list of groups, but `bundler config` needed a ":" separated list of groups (see https://bundler.io/v2.0/man/bundle-config.1.html).

*Mitigation*
Add this setting:
`set :bundle_without, %w{development test}.join(':')`

**Comment by jasonperrone** [comment]
Still seeing this problem in 2.0.1.
