### ISSUE TITLE
cap deploy gets stuck at [bundler:install] Checking Gemfile and Gemfile.lock changes

### ISSUE THREAD

**Issue by gajendrajena** [capistrano/bundler#134]
just facing this issue from last couple of weeks.

deploy gets stuck at` [bundler:install] Checking Gemfile and Gemfile.lock changes`
Surprisingly bundle install on the release folder works fine.

![image](https://github.com/user-attachments/assets/010ea26d-cc58-47f4-b2cc-e1dde07382a8)

ruby version: 2.7.3
bundler: 2.4.22
rails (6.1.6)

![image](https://github.com/user-attachments/assets/b4b1aea5-632f-493c-b272-832168f1ce72)

`git diff --name-only ... `shows around 50 file changes, but the changes are very minimal.

I had this issue earlier, when I split the commit to smaller chunks, it worked fine. 
But when I squashed and try them in another environment it failed again.

there was an old closed issue [#50](https://github.com/capistrano/bundler/issues/50)

**Comment by gajendrajena** [comment]
there was an old closed issue reported 
[issue#50](https://github.com/capistrano/bundler/issues/50)

**Comment by mattbrictson** [comment]
Hi @gajendrajena , do you know where the "Checking Gemfile and Gemfile.lock changes" message is coming from? I don't believe that is being logged by capistrano-bundler (I searched through the source code and couldn't find it).

**Comment by gajendrajena** [comment]
I also couldn't find any?

**Comment by mattbrictson** [comment]
I searched GitHub and found this project: https://github.com/ifool/capistrano-faster-rails . Are you using that?

I'm not familiar with the project, so I can't say for sure if it might be causing the problem you're seeing. Maybe you could try removing it and see if the `bundler:install` step works without it.

**Comment by mattbrictson** [comment]
Here's where I found the log message: https://github.com/ifool/capistrano-faster-rails/blob/6d5f289352a6f3a835d2a4fdfd4c1001bef9ae78/lib/capistrano/tasks/faster-rails.rake#L64

**Comment by gajendrajena** [comment]
thanks @mattbrictson removing the capistrano-faster-rails worked, saved my day. 
the irony is I have lost 10x time troubleshooting this, than I have saved on deploy

**Comment by mattbrictson** [comment]
Glad you got it working! Cheers
