### ISSUE TITLE
Resolve bundle bin location via SSHKit's command_map

### ISSUE THREAD

**Issue by slnovak** [capistrano/bundler#34]
In the `:map_bins` task, should we be resolving the path to `bundle` using `SSHKit.config.command_map.prefix[:bundle]`? For example, I think that:

``` ruby
SSHKit.config.command_map.prefix[command.to_sym].push("bundle exec")
```

should become:

``` ruby
bundle_exec = "#{SSHKit.config.command_map.prefix[command.to_sym] || :bundle} exec"
SSHKit.config.command_map.prefix[command.to_sym].push(bundle_exec)
```

I'm having trouble trying to get capistrano/bundler's `bundle` command to resolve to the bin set by capistrano/rbenv.

Cheers!

**Comment by will-in-wi** [comment]
I think with the introduction of `capistrano-rbenv` and `capistrano-rvm`, this isn't an issue anymore. Feel free to reopen if not the case.
