### ISSUE TITLE
RAILS_ENV is not added to SSHKit commands

### ISSUE THREAD

**Issue by emirkin** [capistrano/bundler#44]
While the gem prefixes `:rake`, `:rails` and other commands with `bundle exec`, it misses  RAILS_ENV. Shouldn't that also be part of remapping?

**Comment by betesh** [comment]
IMO that should really be the job of capistrano-rails, who already handles it pretty cleanly.  If you're interested in submitting a PR for this, I recommend submitting it to capistrano-rails.

**Comment by will-in-wi** [comment]
This is done by `capistrano-rails` now.
