### ISSUE TITLE
Don't generate binstubs by default when using Rails 4?

### ISSUE THREAD

**Issue by Confusion** [capistrano/bundler#45]
When using Rails 4, the default options result in this error being raised when running a command from `bin` in a deployed environment:
```
Looks like your app's ./bin/rails is a stub that was generated by Bundler.

In Rails 4, your app's bin/ directory contains executables that are versioned
like any other source code, rather than stubs that are generated on demand.

Here's how to upgrade:

  bundle config --delete bin    # Turn off Bundler's stub generator
  rake rails:update:bin         # Use the new Rails 4 executables
  git add bin                   # Add bin/ to source control

You may need to remove bin/ from your .gitignore as well.

When you install a gem whose executable you want to use in your app,
generate it and add it to source control:

  bundle binstubs some-gem-name
  git add bin/new-executable
```

I have in fact checked in a `bin` with executables generated by Rails, but they are not used, because by default `bin` is symlinked to `shared/bin`, containing executables with bundler-generated executables. Of course it is trivial to configure bundler such that this doesn't happen, but since *everyone* using Rails 4 needs to do that, it would be better to  just do 'the right thing' out of the box.

Do you agree and are you interested in a pull request for this?

Edit:
Also see https://github.com/rails/rails/issues/8974 and specifically https://github.com/rails/rails/issues/8974#issuecomment-22993215

**Comment by davestephens** [comment]
<insert generic "worked for me to" comment here>

**Comment by Confusion** [comment]
So I haven't ever implemented this, since (AFAIK) no one with commit permissions has given the thumbs up. I have no idea whether there is a reasonable chance of a contribution being merged.

**Comment by leehambley** [comment]
@kirs has the final say :)

**Comment by mustmodify** [comment]
@tisba: I would be interested in hearing the thinking behind why it works this way.

**Comment by tisba** [comment]
@mustmodify not sure what you are referring to… This issue is about to change the default behavior of `capistrano-bundler`

**Comment by mustmodify** [comment]
Sorry I wasn't clear. When I deploy, it seems that capistrano replaces my bin directory, leaving me without the files in my repo. You said, "Honestly, I won't change capistrano-bundlers default behavior here." So I assume there is some good reason why you think the current behavior is appropriate. It may be a great reason that I just don't understand. Would you care to enlighten me / us?

**Comment by tisba** [comment]
I only changed the `set :linked_dirs` to "fix" this issue with Rails:

```
set :linked_dirs, %w{log tmp/pids tmp/cache tmp/sockets vendor/bundle public/system}
```

But I have another project that uses `capistrano-bundler` which is not a rails project. One solution could be some kind of auto detection magic to figure out if you are deploying a rails app (or `capistrano-rails` could do that).

**Comment by kirs** [comment]
Thanks to everyone. This is really an issue.

I'm going to make 2 things:
1) `bin/` won't be recommended to be symlinked in the `deploy.rb` template: https://github.com/capistrano/capistrano/pull/1321
2) `binstubs` won't be generated by default inside `capistrano-bundler`: https://github.com/capistrano/bundler/pull/61

**Comment by kirs** [comment]
Any thoughts?

**Comment by blackjid** [comment]
:+1:

**Comment by indirect** [comment]
I also recommend this. The "official recommendation" is to run `bundler binstubs delayedjob` (or whichever gem) to create a single binstub for the gem you need, and commit that binstub into git. Capistrano shouldn't need to generate its own binstubs, and definitely shouldn't overwrite the Rails 4 generated binstubs.

**Comment by kirs** [comment]
@indirect thanks!

**Comment by kirs** [comment]
`capistrano-bundler` 1.1.4 without auto binstubs generation released.

**Comment by kirs** [comment]
Both PRs are merged. Thanks for discussion. Can be closed now.

**Comment by unabl4** [comment]
:+1:

**Comment by sunil-netsol** [comment]
:+1: worked for me.

**Comment by theB264** [comment]
The solution from @jweslley also worked for me. :+1:

**Comment by Frrank1** [comment]
bundle --binstubs is any off you know what this do.

**Comment by Frrank1** [comment]
I mean the full documentation. i cold not find it

**Comment by mattbrictson** [comment]
@Frrank1 I think the only place in the official document where binstubs is explained is here: http://bundler.io/v1.11/man/bundle-exec.1.html

**Comment by Frrank1** [comment]
Hey thanks @mattbrictson

**Comment by u007** [comment]
i think this configuration should be the default config/deploy.rb
http://stackoverflow.com/questions/36347033/rails-5-console-not-working

what do you guys think?

**Comment by Frrank1** [comment]
@u007  it's the same solution as @jweslley  and @mattbrictson suggested.

**Comment by waleedarshad** [comment]
(y)

**Comment by gregblass** [comment]
Thank you @jweslley. After 2+ hours fighting to get my app to deploy with webpack, removing 'bin' from linked_dirs finally worked for me.
