### ISSUE TITLE
The bundler install time is too long every time.

### ISSUE THREAD

**Issue by wcc526** [capistrano/bundler#50]
When I run the `cap production deploy' and I will get stuck in this operation every time,

 
&& ~/.rvm/bin/rvm default do bundle install --binstubs /var/www/test-project/shared/bin --path /var/www/test-project/shared/bundle --without development test --deployment --quiet

Why?

**Comment by ijunaid8989** [comment]
I am having the same issue. I have only one application.

I installed ruby through RVM there and did nothing else. only the required things. But Its stuck on 
``
~/.rvm/bin/rvm default do bundle install --path /home/deployer/apps/evercam-admin/shared/bundle --without development
```

**Comment by errawn** [comment]
same is happening to me. just stucked with this errors: almost 10 mins now.

![image](https://user-images.githubusercontent.com/18679035/83838492-eb387700-a72b-11ea-9098-451d60328a71.png)


also whenever it is running, I cannot connect to my ec2 instance. is this expected?

**Comment by cbrandt-it** [comment]
Have you found a solution, @errawn ? I'm having the exact same problem.

**Comment by tkoutangni** [comment]
I had the same issue so this is what i tried to solve it. i remove the releases/ and current folder and redeploy the app. It was fast this time. Let me know if that works for you too.
