### ISSUE TITLE
Detection of Gemlock changed since last deployment

### ISSUE THREAD

**Issue by sahin** [capistrano/bundler#54]
It will be super super great if we have that feature like https://github.com/tomafro/recap.

**Comment by kirs** [comment]
Thanks for your suggestion. Please check #54.

**Comment by sahin** [comment]
Wow, thx, it will save so so so much time from some many developers. I think we should put this in readme. 

Can you dump the version?

**Comment by sahin** [comment]
@kirs we are using in production now, and we deployed more than 50 times for 3 web projects, 12 workers, api , it seems it is working perfect.
