### ISSUE TITLE
Bundle roles not according to the documentation (readme file)

### ISSUE THREAD

**Issue by gamafranco** [capistrano/bundler#56]
According to the documentation, the default for :bundle_roles is :all, but when you try it, the :bundle_roles variable is not set.

Using version capistrano-bundler 1.1.3.

**Comment by Kriechi** [comment]
Not sure what you mean, but `bundle_roles` and `bundle_servers` are set here:
https://github.com/capistrano/bundler/blob/master/lib/capistrano/tasks/bundler.cap#L64

Could you show a bit of your configuration and Capfile?

**Comment by gamafranco** [comment]
Thanks for getting back. To be honest I don't remember in which project I got this, so I can't provide an example.

Closing for now. Will reopen if I bump into it again.

Thanks.
