### ISSUE TITLE
Run `Bundler.setup` when `capistrano/bundler` is required in app Capfile

### ISSUE THREAD

**Issue by amw** [capistrano/bundler#57]
Currently when you run `cap` Capistrano will use system load path instead of those defined in your app Gemfile. If you use your Gemfile to select alternate versions of some Capistrano gems, say `gem "capistrano-rails", path: "../capistrano-rails"` you have to run `bundle exec cap` for your changes to have effect.

An alternative is to add these lines to your Capfile:

```
require "bundler"
Bundler.setup
```

I think one could expect `require "capistrano/bundler"` to make the `cap` command fully bundler-aware. Meaning: tasks should be loaded from sources specified in Gemfile. That's how `rails` and `rake` commands behave in Rails projects.

Since we don't want to reference bundler in the default Capfile template, I think those two lines should be ran in `lib/capistrano/rails.rb`. That way when user explicitly requires bundler support with his Capfile, the load path is automatically set for him.

**Comment by will-in-wi** [comment]
I think the preferred solution for this issue are binstubs. Run `bundle binstub capistrano` in your project, and then run `bin/cap`. This is frequently committed to the repo.
