### ISSUE TITLE
Automatically install correct bundler version – is this a desirable feature?

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/bundler#70]
The bundler team advocates using the latest release of bundler to avoid bugs in older versions, and has even gone so far as adding a `BUNDLED WITH` entry to the Gemfile.lock. The idea is that **the version of bundler you use in development should match the version of bundler you use in production.**

I propose that capistrano-bundler should help do this.

Basically, just before `bundle:install`, we should:

1. Parse the Gemfile.lock to check the `BUNDLED WITH` version
2. If it specifies a newer version of bundler, use `gem install bundler` to install it

This would ensure that `cap deploy` would keep your server up to date with the version of bundler that your app requires.

Does this sound like a useful feature? I will contribute a PR if there is interest.

**Comment by sahin** [comment]
+1

**Comment by jstr** [comment]
Just want to note that this behaviour could be problematic in some scenarios. An example is where `gem` in `PATH` is not used to install `bundler`, but an alternative binary.

Here's a snippet from a chef recipe:

```ruby
gem_package "bundler" do
  action :upgrade
  gem_binary "/usr/bin/gem2.0"
end
```

This installs bundler at `/usr/local/bin/bundle` on Ubuntu/Debian, so running `gem install bundler` would not have the desired effect.

**Comment by mattbrictson** [comment]
@jstr Would allowing the `gem install bundler` command to be configurable address your concern? Or do you think this feature would in general cause more headaches than it's worth?

**Comment by jstr** [comment]
I think that would address this issue. However it's reasonably common to manage the bundler gem on servers with tools like Chef and Puppet, so you could make the argument that it would be correct to leave the installation of the correct bundler version in the hands of the user. Perhaps it should be optional?

**Comment by mattbrictson** [comment]
@jstr Hmm, I think you're right, that bundler, like Ruby, is really a server provisioning concern and usually better served by other tools. Maybe it's best not to include this as a core capistrano-bundler feature.

**Comment by mattbrictson** [comment]
If anyone stumbles across this issue and is interested, you can see an implementation of the auto-install-bundler feature here:

https://github.com/mattbrictson/capistrano-mb/blob/61f2fe9d6416359110e93f9aab91e82faac0543e/lib/capistrano/tasks/bundler.rake
