### ISSUE TITLE
Make capistrano-bundler install bundler if it is missing

### ISSUE THREAD

**Issue by donv** [capistrano/bundler#74]
We use capistrano-rvm during deployment, and it will occasionally install a new Ruby version for running the application.  In this case Bundler is not installed, and capistrano-bundler cannot do its magic.

Can you add a simple

```
gem query -i -n bundler || gem install bundler
```

to capistrano-bundler to make sure bundler is actually installed before running `bundle install` ?

**Comment by emaillenin** [comment]
I have installed bundler manually in the production server, but I still get the error:

     Could not find 'bundler' (>= 0) among 13 total gem(s)

Full deploy output [here](https://gist.github.com/emaillenin/47ab38acef73f8feae3e).

**Comment by donv** [comment]
@emaillenin submit your own issue.  This is a feature request.

**Comment by skalee** [comment]
Stumbled upon same problem (no bundler on fresh Ruby installation). However I'm not sure if automatic installation is a good idea. No bundler problem may be a result of misconfiguration, in such case forced install to unexpected location will result in deploying semi-functional system and hiding real problem from user.

**Comment by mattbrictson** [comment]
Related: #70 (auto install correct bundler version)

**Comment by will-in-wi** [comment]
Is this still something people want? IME, Bundler on a production server involves root access, which the deployment doesn't have. I'm sure that there are exceptions, but I don't know that this is common enough to be worth including in core.

Given this ticket's age, I'm closing. Feel free to reopen if still desired.
