### ISSUE TITLE
how to switch off prefixing gem command by 'bundle exec' on some time 

### ISSUE THREAD

**Issue by northbear** [capistrano/bundler#75]
Hi! 
For initial tasks of capistrano it is sometime required to switch off adding prefix 'bundle exec' to gem command. Before fetching sources from remote repository Gemfile may absent on prelease_path, but some specific gem should be installed. 
What is a easiest way to do it?

**Comment by dmolesUC3** [comment]
+1! For example, this task should install bundler, but it fails.

```
namespace :install do
  desc 'Install/update bundler'
  task :bundler do
    on roles(:all) do |host|
      if test('which bundle')
        info "Bundler is already installed on #{host}"
        execute :gem, 'update', "'^bundler$'"
      else
        execute :gem, 'install', 'bundler'
      end
    end
  end
end
```

Instead of running `gem install bundler`, it runs `bundle exec gem install bundler`, resulting in:

```
DEBUG [727a18b6] Command: bundle exec gem install bundler
DEBUG [727a18b6]        bash: bundle: command not found
```

Is there a workaround?

**Comment by dmolesUC3** [comment]
As a workaround, I used `sh -c`:

```
execute "sh -c 'gem update \"^bundler$\"'"
```

and

```
 execute 'sh -c "gem install bundler"'
```

**Comment by mattbrictson** [comment]
Hi, you could also bypass the prefixing behavior by using a single string argument to `execute`, like this:

```ruby
# This bypasses SSHKit's command-prefix behavior
execute "gem install bundler"
```

Or, if you never want `gem` to be prefixed, you can exclude it when setting `bundle_bins`:

```ruby
# This the default
# set :bundle_bins, %w(gem rake rails)
set :bundle_bins, %w(rake rails)
```

**Comment by realhugh08** [comment]
Ran into the same problem!

What is the logic for prefixing gem by bundle exec, when would that apply?
As far as I know there is only one rubygems installation per ruby?

Any explanation would be awesome, thanks!

**Comment by mattbrictson** [comment]
I'm also fuzzy on why someone would ever use `bundle exec gem`, but it does have an effect. If you run `gem list` you get all gems in your Ruby, vs `bundle exec gem list` will show only show gem versions that match your Gemfile.lock.

**Comment by realhugh08** [comment]
Ok thanks you're right, it does seem to have an effect.
But is it wise to have it set as the default behavior?

I personally always want to call the "real" gem, especially during setup, so I fixed it with:
```ruby
set :bundle_bins, %w(rake rails)

# If wished, calling bundle exec gem could be easily done
execute(:bundle, :exec, :gem, ...)
```
But this could be a frustrating issue for new users who just want to call "gem".
This is maybe just my opinion, great work by the way!

**Comment by mattbrictson** [comment]
I agree, I don't need `bundle exec gem` either, but changing that now could break deploys of users that expect that default behavior. There is an easy workaround, so perhaps better documentation is the solution?

**Comment by realhugh08** [comment]
I understand, maybe a hint to this behavior could be put on the readme of capistrano-rails, since many users will read capistrano-rails but not necessarily capistrano-bundler, but once you know the documentation here is pretty good.

Like I said I'm good now, since I know the behavior, but could be frustrating for new users. At first I thought it was [rvm1-capistrano3](https://github.com/rvm/rvm1-capistrano3) who was responsible, but finally troubleshooted it here.

Anyway, thanks for your time dude!

**Comment by will-in-wi** [comment]
It seems like this is more of a documentation issue if anything. If anyone wants to submit a PR for that, go for it!

However, given the age of this ticket, I'm closing. If anyone wants it to stay open, feel free to reopen.
