### ISSUE TITLE
Can't get `bundle install` step to print anything

### ISSUE THREAD

**Issue by vemv** [capistrano/bundler#76]
Event if I replace the `--quiet` flag for `--verbose`, one is unable to see any output from `bundle install`, which can be useful for getting an idea of the installation progress (staring 2 minutes at a still screen isn't very cool).

Screenshot:

![screen shot 2015-10-26 at 20 40 53](https://cloud.githubusercontent.com/assets/1162994/10740329/fa641aca-7c21-11e5-8a6d-f75dbad559ff.png)

**Comment by vemv** [comment]
(running on AWS. Bundle install will succeed, but I find the lack of output unsettling)

**Comment by mattbrictson** [comment]
You need `set :log_level, :debug` in order to see command output. Otherwise the default capistrano formatter only prints the command string and the exit status.

**Comment by vemv** [comment]
Ah, I see. Cap newbie here. Thanks much!

Victor
