### ISSUE TITLE
Option to disable "--deployment" flag in bundle command

### ISSUE THREAD

**Issue by MichaelSp** [capistrano/bundler#8]
As I develop on Windows I cannot reuse the Gemfile.lock because the gemfiles are not the same on my deployment system (Linux).
The --deployment flag requires exactly that.
So I need an option to remove the --deployment from the command 

```
~/.rvm/bin/app_bundle --gemfile /usr/share/nginx/www/staging/app/releases/20131017081800/Gemfile --path /usr/share/nginx/www/staging/app/shared/bundle --deployment --quiet --binstubs /usr/share/nginx/www/staging/app/shared/bin --without [:test, :development]
```

Error (if Gemfile.lock is not in scm)

```
                Cannot write a changed lockfile while frozen.
INFO [22519c68] Finished in 11.163 seconds command successful.
```

Side note: The command is actually NOT successful...

**Comment by AlekhyaR** [comment]
thanks @MichaelSp it worked for me too
