### ISSUE TITLE
Please tag version 1.1.3

### ISSUE THREAD

**Issue by paulmenzel** [capistrano/bundler#82]
The tag for version 1.1.3 is missing.

```
$ git tag
1.0.0
v1.1.0
v1.1.1
v1.1.2
v1.1.4
```

Could you please add it?

**Comment by mattbrictson** [comment]
Unfortunately it looks like there is no commit that corresponds to 1.1.3. Perhaps someone forgot to push the commit and the tag to GitHub.

The closest I could find b6e609d plus 77af8c5. That matches the 1.1.3 gem on Rubygems with the exception of a minor README edit.

```diff
< set :bundle_bins, fetch(:bundle_bins, []).push 'my_new_binary'
---
> set :bundle_bins, fetch(:bundle_bins, []).push %w(my_new_binary)
```

@kirs can you help?

Otherwise I'll recreate the necessary commit and tag it.

**Comment by paulmenzel** [comment]
I thought it would be commit c1f902e0 (Prepare for 1.1.2), which just has a typo in the commit message. But I didn’t compare it with the published Gem.

**Comment by mattbrictson** [comment]
That's almost right. But it is different than the published gem like this:

```diff
<   spec.add_development_dependency 'rake'
---
>   spec.add_development_dependency 'rake', '~> 0'
```

Which I believe is c3e7356.

**Comment by mattbrictson** [comment]
So I can branch off of c1f902e and cherry pick c3e7356 and use that to recreate the missing commit, and tag it `v1.1.3`. Sound good?

**Comment by paulmenzel** [comment]
@mattbrictson, interesting, thank you for the analysis.

Your proposal sounds good. Although it would be quite some hassle, as branches have not been used yet for these kind of things in this project, right?

Another solution would be to tag the closest commit *v1.1.3-almost* or so, and leave it be.

But let’s wait for @kirs to see if more light can be shed into this.

**Comment by kirs** [comment]
It was absolutely my fault that I forgot about `rake release` (which creates a tag) and went with `gem build && gem push`.

`v1.1.3-almost` sounds good for me.

**Comment by mattbrictson** [comment]
I can recreate the commit and then we will have an *exact* `v1.1.3` tag, which will be much more valuable, IMHO. It really is no trouble for me to do it.

**Comment by kirs** [comment]
Thank/you for the help!

On May 6, 2016 11:46, "Matt Brictson" <notifications@github.com> wrote:
>
> I can recreate the commit and then we will have an exact v1.1.3 tag,
which will be much more valuable, IMHO. It really is no trouble for me to
do it.

**Comment by mattbrictson** [comment]
OK I've created the `v1.1.3` tag. It exactly matches the 1.1.3 gem at Rubygems.
